//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cedar_policy_set")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub policy_id: i32,
    pub annotation: String,
    #[sea_orm(column_type = "Text")]
    pub policy_text: String,
    pub effect: String,
    #[sea_orm(custom_type = "i8")]
    pub is_active: bool,
    pub description: String,
    #[sea_orm(unique)]
    pub policy_hash: String,
    pub policy_type: String,
    #[sea_orm(unique)]
    pub policy_uuid: String,
    pub created_by: i32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::template_links::Entity")]
    TemplateLinks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::template_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateLinks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
