//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod auditlog;
pub mod cluster_config;
pub mod departments;
pub mod group_roles;
pub mod roles;
pub mod systems;
pub mod user_group_members;
pub mod user_groups;
pub mod user_roles;
pub mod users;
pub mod cedar_policy_set;
pub mod cedar_schema;
pub mod template_links;